/*
 * File: content/glossary.js
 * Purpose: The general glossary: every business term and acronym in plain English (US-1.6.3).
 * Provides: window.TAP_CONTENT.glossary
 * Depends on: nothing
 * Used by: js/core/content.js, js/ui/glossary.js, js/views/guide.js
 *
 * Entry format: id: { term, aliases: [], short: 'one or two sentences', why: 'why it matters here', related: [ids] }
 * - term is the name shown in the A to Z list; aliases are other words for the same thing (plural "s" is automatic).
 * - Words are marked on screen wherever they appear, so an alias must not be an everyday word.
 * - No word may belong to two entries. The organization layer (content/organization.js) adds its own terms
 *   and wins over an entry here with the same id.
 */
window.TAP_CONTENT = window.TAP_CONTENT || {};
window.TAP_CONTENT.glossary = Object.assign(window.TAP_CONTENT.glossary || {}, {
  // Planning
  tap: { term: 'Territory account plan', aliases: ['TAP', 'territory account planning', 'territory plan'],
    short: 'A plan each regional leader writes for the next three years. It says which industries to focus on, which customers to grow, and how to sell and with whom.',
    why: 'This app shows every region’s plan side by side, so leaders can see where they agree and where they differ.', related: ['operationalPlanning', 'planYear'] },
  operationalPlanning: { term: 'Operational planning', aliases: ['operating plan'],
    short: 'The yearly work of turning a plan into budgets: headcount, marketing, partner and product decisions.',
    why: 'Territory account plans feed it. What the regions agree on here shapes where resources go next.', related: ['tap'] },
  planYear: { term: 'Plan year', aliases: ['Year 1', 'Year 2', 'Year 3', 'plan years'],
    short: 'The three years a plan covers, called Year 1, Year 2 and Year 3.',
    why: 'Most figures are given per plan year or as the three-year total. The chart says which.', related: ['ambition'] },
  ambition: { term: 'Ambition', aliases: ['three-year ambition', '3-year ambition'],
    short: 'The new business a region plans to win over the three plan years: new business plus customer growth.',
    why: 'It is the headline size of each plan, and the first thing the Overview compares.', related: ['newBusiness', 'customerGrowth', 'orderIntake'] },
  industry: { term: 'Industry', aliases: ['industries', 'vertical'],
    short: 'A type of customer business, such as healthcare or education. Every plan uses the same fixed list.',
    why: 'Leaders rate and rank the same industries, so their choices can be compared directly.', related: ['tier', 'subVertical'] },
  subVertical: { term: 'Sub-vertical', aliases: ['sub-industry', 'subvertical'],
    short: 'A narrower slice of an industry in one market, such as large university campuses within education.',
    why: 'New business plans are built per sub-vertical, which shows how precisely a region has targeted its customers.', related: ['industry', 'market'] },
  market: { term: 'Geographic market', aliases: ['local market'],
    short: 'The country or part of a region where a sub-vertical is targeted.',
    why: 'It shows where in the region new customers are expected to come from.', related: ['subVertical'] },
  productLine: { term: 'Product line', aliases: ['product lines'],
    short: 'A family of products sold together. Each industry is served by one product line.',
    why: 'Charts can be grouped by product line to see which part of the offer a plan leans on.', related: ['industry', 'productFit'] },
  commentary: { term: 'Commentary', aliases: ['leader commentary'],
    short: 'Free text a leader wrote next to an industry to explain a rating or a choice.',
    why: 'It gives the reasons behind the numbers. Read it before drawing conclusions about a region.', related: ['leaderInput', 'rating'] },
  successFactors: { term: 'Key success factors', aliases: ['success factors', 'key success factor'],
    short: 'What a leader says is needed to win a sub-vertical, such as marketing material, product changes or specialist partners.',
    why: 'They show what other teams would need to provide for a plan to work.', related: ['subVertical', 'newBusiness'] },

  // Tiers and ratings
  tier: { term: 'Tier', aliases: ['tiering'],
    short: 'How much priority a region gives an industry: Tier 1 group priority, Tier 2 focus, Tier 3 opportunistic.',
    why: 'Tiers show where each region plans to put its effort. Agreement and disagreement across regions is a key topic.', related: ['groupPriority', 'focusTier', 'opportunistic'] },
  groupPriority: { term: 'Group priority', aliases: ['Tier 1', 'group-priority'],
    short: 'An industry set as Tier 1 for every region by central strategy. Leaders don’t choose it.',
    why: 'These industries are marked so a reader knows the tier was given, not chosen.', related: ['tier', 'focusTier'] },
  focusTier: { term: 'Focus tier', aliases: ['Tier 2'],
    short: 'An industry a region chose to invest in because it has a winning recipe there.',
    why: 'Tier 2 choices are the leader’s own bets, so they say most about local judgement.', related: ['tier', 'opportunistic'] },
  opportunistic: { term: 'Opportunistic tier', aliases: ['Tier 3', 'opportunistic'],
    short: 'An industry a region will sell to when a chance comes up, with no active investment.',
    why: 'Tier 3 industries get no new business plan, so they add little to the ambition.', related: ['tier', 'focusTier'] },
  rating: { term: 'Rating', aliases: ['rating scale'],
    short: 'A leader’s judgement of an industry on a three-step scale, scored 1 to 3. Three is always the favourable end.',
    why: 'Each industry gets six ratings. They build the two scores on the attractiveness chart.', related: ['score', 'attractiveness', 'ability'] },
  growthPotential: { term: 'Growth potential', aliases: ['market dynamism'],
    short: 'How much the industry is growing locally and how much business is left to win.',
    why: 'One of the three ratings behind attractiveness.', related: ['attractiveness', 'rating'] },
  criticality: { term: 'Criticality', aliases: ['criticality of our offering'],
    short: 'How important the offer is to the customer’s results, from business critical to limited value.',
    why: 'One of the three ratings behind attractiveness.', related: ['attractiveness', 'rating'] },
  competitiveIntensity: { term: 'Competitive intensity', aliases: ['competitive pressure'],
    short: 'How strong the competition is. A score of 3 means the region is the recognized leader; 1 means strong competitors dominate.',
    why: 'One of the three ratings behind attractiveness. Higher is better, like every other rating.', related: ['attractiveness', 'rating'] },
  references: { term: 'References', aliases: ['reference', 'strong references'],
    short: 'Existing customers in the industry who can vouch for the offer, from top local players down to none.',
    why: 'One of the three ratings behind ability to win.', related: ['ability', 'rating'] },
  expertise: { term: 'Expertise', aliases: ['in-house expertise'],
    short: 'How much know-how about the industry the region has in its own team.',
    why: 'One of the three ratings behind ability to win.', related: ['ability', 'rating'] },
  productFit: { term: 'Product fit', aliases: ['product gaps'],
    short: 'How well the products meet the industry’s needs, from strong to major gaps.',
    why: 'One of the three ratings behind ability to win. Gaps here often point to product requests.', related: ['ability', 'rating', 'productLine'] },
  score: { term: 'Score', aliases: ['two scores'],
    short: 'A figure this app calculates from ratings. Each score is the average of three ratings, from 1 to 3.',
    why: 'There are two: attractiveness and ability to win. Together they place each industry on the chart.', related: ['attractiveness', 'ability', 'rating'] },
  attractiveness: { term: 'Attractiveness', aliases: ['attractiveness score'],
    short: 'How appealing an industry is: the average of growth potential, criticality and competitive intensity.',
    why: 'It is the up axis of the attractiveness chart. High scores mark markets worth pursuing.', related: ['score', 'ability', 'quadrant'] },
  ability: { term: 'Ability to win', aliases: ['ability-to-win score'],
    short: 'How well placed a region is to win in an industry: the average of references, expertise and product fit.',
    why: 'It is the across axis of the attractiveness chart. Low scores in attractive markets show where help is needed.', related: ['score', 'attractiveness', 'quadrant'] },
  quadrant: { term: 'Quadrant', aliases: ['four areas', 'midpoint'],
    short: 'One of the four areas of the attractiveness chart, split where each score is 2.0. A score of exactly 2.0 counts as high.',
    why: 'The area an industry falls in suggests a different conversation: invest, build capability, maintain or deprioritize.', related: ['attractiveness', 'ability'] },

  // Revenue and pipeline
  arr: { term: 'ARR', aliases: ['annual recurring revenue', 'recurring revenue', 'current ARR'],
    short: 'Annual recurring revenue: what customers pay each year for ongoing subscriptions and contracts.',
    why: 'Most plan figures are ARR. Current ARR shows where a region is today; new ARR shows what it plans to add.', related: ['arrPotential', 'orderIntake', 'services'] },
  arrPotential: { term: 'ARR potential', aliases: ['new business ARR potential'],
    short: 'The new ARR a sub-vertical could bring: target accounts × hit rate × average deal size.',
    why: 'It is how each new business row turns a leader’s inputs into money, and it is calculated in the workbook.', related: ['targetAccounts', 'hitRate', 'avgDealSize'] },
  services: { term: 'Services', aliases: ['services order intake', 'professional services'],
    short: 'One-off work sold alongside products, such as setup, consulting and training.',
    why: 'Plans show services next to ARR, so the full order intake can be compared.', related: ['servicesRatio', 'orderIntake'] },
  servicesRatio: { term: 'Services ratio', aliases: ['services ratios'],
    short: 'Services sold for each unit of ARR, as a percentage. A ratio of 30% means 30 of services for every 100 of ARR.',
    why: 'It turns ARR into a services figure. A ratio far from other regions is worth a question.', related: ['services', 'arr'] },
  orderIntake: { term: 'Order intake', aliases: ['total order intake', 'OI'],
    short: 'The value of new orders signed in a period: new ARR plus services.',
    why: 'It is the widest measure of a plan’s size and is used for channel and segment views.', related: ['arr', 'services', 'ambition'] },
  pipeline: { term: 'Pipeline', aliases: ['pipeline total', 'open pipeline'],
    short: 'The value of sales opportunities that are open now and not yet won or lost.',
    why: 'It is a system figure that shows how much a region is already working on in each industry.', related: ['pipelineCreated', 'systemFigure'] },
  pipelineCreated: { term: 'Pipeline created', aliases: ['pipeline created in the last 12 months', 'new pipeline'],
    short: 'The value of new sales opportunities opened in the last 12 months.',
    why: 'It shows recent momentum. Total pipeline can be old; pipeline created shows what is happening now.', related: ['pipeline'] },
  newBusiness: { term: 'New business', aliases: ['new customers'],
    short: 'Revenue from customers who don’t buy from us yet.',
    why: 'One of the two parts of every plan. Its size depends on target accounts, hit rate and deal size.', related: ['customerGrowth', 'arrPotential', 'ambition'] },
  customerGrowth: { term: 'Customer growth', aliases: ['existing customers', 'growth from existing customers'],
    short: 'Extra revenue from customers who already buy from us, through more products, users or sites.',
    why: 'The other part of every plan. A region leaning heavily on it depends on its current customers.', related: ['newBusiness', 'segment', 'ambition'] },
  targetAccounts: { term: 'Target accounts', aliases: ['accounts to target', 'target pool', 'target account'],
    short: 'The number of potential customers a region plans to pursue in a sub-vertical.',
    why: 'Together with the hit rate it shows whether the pool is big enough for the ambition.', related: ['hitRate', 'impliedWins', 'arrPotential'] },
  hitRate: { term: 'Hit rate', aliases: ['win rate'],
    short: 'The share of targeted accounts a region expects to win, as a percentage.',
    why: 'A high hit rate makes a plan depend on winning most of what it targets. Compare it with other regions.', related: ['targetAccounts', 'impliedWins'] },
  impliedWins: { term: 'Implied wins', aliases: ['expected wins'],
    short: 'How many new customers a plan expects: target accounts × hit rate. This app calculates it.',
    why: 'It turns percentages into a count of customers that is easy to compare.', related: ['targetAccounts', 'hitRate', 'avgDealSize'] },
  avgDealSize: { term: 'Average deal size', aliases: ['deal size', 'average deal'],
    short: 'The ARR a region expects from each new customer it wins, on average.',
    why: 'Large differences between regions selling to the same industry are worth discussing.', related: ['arrPotential', 'hitRate'] },
  growthAssumption: { term: 'Growth assumption', aliases: ['growth assumptions', 'growth %'],
    short: 'How much a leader expects revenue to grow from one plan year to the next, before any price increase.',
    why: 'It drives Year 2 and Year 3. Small changes add up over three years.', related: ['planYear', 'newBusiness', 'customerGrowth'] },

  // Customers and segments
  segment: { term: 'Segment', aliases: ['segmentation', 'account segment'],
    short: 'A group of existing customers handled the same way: strategic, growth, core or scaled.',
    why: 'Segments show where effort goes among current customers. The workbook sets them by a fixed rule.', related: ['segStrategic', 'segGrowth', 'segCore', 'segScaled', 'segmentationRule'] },
  segmentationRule: { term: 'Segmentation rule', aliases: ['segment thresholds', 'threshold', 'thresholds'],
    short: 'The rule that puts each customer in a segment, using limits on current ARR and planned order intake that the leader sets.',
    why: 'Each region sets its own limits, so the same customer could land in different segments in different regions.', related: ['segment'] },
  segStrategic: { term: 'Strategic segment', aliases: ['strategic accounts', 'strategic account'],
    short: 'Customers whose current ARR is above the strategic limit. They are checked first.',
    why: 'The largest customers, who usually get dedicated attention.', related: ['segment', 'segmentationRule'] },
  segGrowth: { term: 'Growth segment', aliases: ['growth accounts', 'growth account'],
    short: 'Customers with high planned order intake and ARR above the growth limit.',
    why: 'Where the plan expects the most expansion. Worth checking the growth is realistic.', related: ['segment', 'customerGrowth'] },
  segCore: { term: 'Core segment', aliases: ['core accounts', 'core account'],
    short: 'Customers that are not strategic, growth or scaled.',
    why: 'Usually the bulk of the customer list, kept and grown steadily.', related: ['segment'] },
  segScaled: { term: 'Scaled segment', aliases: ['scaled accounts', 'scaled account'],
    short: 'Customers whose current ARR is below the scaled limit.',
    why: 'Small customers, often served through lighter-touch or partner channels.', related: ['segment', 'channel'] },
  accountRisk: { term: 'Account risk', aliases: ['risk level', 'high risk'],
    short: 'A system flag of high or medium risk that a customer may reduce or stop buying.',
    why: 'Growth planned on high-risk customers is less certain.', related: ['customerGrowth', 'systemFigure'] },

  // Channels
  channel: { term: 'Channel', aliases: ['sales channel', 'channel split'],
    short: 'The route to the customer: direct, through partners, or through alliances.',
    why: 'Each new business row splits its value across channels, which shows how much a plan relies on others.', related: ['direct', 'partner', 'alliance'] },
  direct: { term: 'Direct channel', aliases: ['direct sales'],
    short: 'Selling with the region’s own sales team, with no partner in between.',
    why: 'The channel a region controls most closely.', related: ['channel', 'partner'] },
  partner: { term: 'Partner', aliases: ['partner channel', 'reseller'],
    short: 'An outside firm that resells or delivers the offer for a share of the value.',
    why: 'Plans that lean on partners need enough capable partners in place.', related: ['channel', 'alliance'] },
  alliance: { term: 'Alliance', aliases: ['Alliance A', 'Alliance B', 'alliance channel'],
    short: 'A larger strategic partner that sells together with the region. The template has two: Alliance A and Alliance B.',
    why: 'Alliance shares show how much a plan depends on these relationships.', related: ['channel', 'partner'] },

  // Kinds of data and figures
  leaderInput: { term: 'Leader input', aliases: ['leader’s rating', 'leader judgement'],
    short: 'A value the regional leader entered from their own judgement, such as a tier, a rating or a hit rate.',
    why: 'The app labels it so you can tell belief from system facts.', related: ['systemFigure', 'calculated'] },
  systemFigure: { term: 'System figure', aliases: ['system pre-fill', 'pre-filled'],
    short: 'A value copied into the workbook from company systems, such as current ARR or pipeline.',
    why: 'It is the same kind of fact for every region, so it is a fair baseline.', related: ['leaderInput', 'calculated'] },
  calculated: { term: 'Calculated figure', aliases: ['calculated in the workbook', 'calculated by this app', 'derived'],
    short: 'A value worked out from other values, either by the workbook’s formulas or by this app.',
    why: 'The source line says which, so you can trace how it was made.', related: ['leaderInput', 'systemFigure'] },
  combined: { term: 'Combined figure', aliases: ['organization total', 'average of the rest', 'total of the other regions'],
    short: 'A figure that joins several regions into one: a total, or an average of the rest. It is drawn in dark grey.',
    why: 'It lets one region be compared with everyone else. Rates are weighted so larger regions count more.', related: ['weightedAverage', 'focusRegion'] },
  weightedAverage: { term: 'Weighted average', aliases: ['weighted mean'],
    short: 'An average where larger items count more. A hit rate over 200 accounts counts more than one over 20.',
    why: 'Rates such as hit rate are combined this way, so small regions don’t distort the result.', related: ['combined', 'hitRate'] },
  focusRegion: { term: 'Focus region', aliases: [],
    short: 'The region you chose in the comparison bar, shown in its own colour against the others.',
    why: 'Insights about the focus region are listed first.', related: ['combined'] },
  notProvided: { term: 'Not provided', aliases: ['blank'],
    short: 'A value the leader left blank. It is never shown as zero.',
    why: 'Gaps are visible, so a missing answer is never mistaken for a low one.', related: ['notApplicable'] },
  notApplicable: { term: 'Not applicable', aliases: ['unrated'],
    short: 'A value the template does not ask for, such as ratings for the catch-all industry rows.',
    why: 'These are left out quietly and never counted as gaps.', related: ['notProvided'] },
  insight: { term: 'Insight', aliases: ['observation to discuss', 'observation'],
    short: 'A short sentence the app writes when a figure stands out, such as wide disagreement between regions.',
    why: 'Insights are prompts for discussion, not verdicts. Each one shows the figures behind it.', related: ['focusRegion'] },
  kAndM: { term: 'k and M', aliases: ['k', 'M', 'thousands', 'millions'],
    short: 'Short for thousands (k) and millions (M). 250k is 250,000 and 1.2M is 1,200,000.',
    why: 'Charts round money this way to stay readable. The table view shows exact figures.', related: ['arr'] },

  // Roles
  cro: { term: 'CRO', aliases: ['Chief Revenue Officer'],
    short: 'Chief Revenue Officer: the executive responsible for all revenue, across sales, partners and customer teams.',
    why: 'The regional plans are reviewed together with the CRO.', related: ['revops', 'tap'] },
  revops: { term: 'RevOps', aliases: ['Revenue Operations'],
    short: 'Revenue Operations: the team that runs the planning process, tools and data for sales.',
    why: 'RevOps collects the regional plans and keeps this app’s data up to date.', related: ['cro', 'tap'] }
});
